Use semantic versioning

diff --git a/.github/workflows/cd-build-and-release.yml b/.github/workflows/cd-build-and-release.yml
--- a/.github/workflows/cd-build-and-release.yml
+++ b/.github/workflows/cd-build-and-release.yml
@@ -28,12 +28,23 @@ jobs:
         uses: actions/checkout@v4
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v3
-      - name: Extract tag information
-        id: tag
+      - name: Extract release information
+        id: release
         run: |
           PRERELEASE=${{ github.event.release.prerelease && 'true' || 'false' }}
           echo "prerelease=$PRERELEASE" >> $GITHUB_OUTPUT
-          echo "tag=${{ github.event.release.tag_name }}" >> $GITHUB_OUTPUT
+      - name: Extract semantic version components
+        id: semver
+        run: |
+          semver_regex="^v?([0-9]+)\.([0-9]+)\.([0-9]+)"
+          if [[ "${{ github.event.release.tag_name }}" =~ $semver_regex ]]; then
+            echo "major=${BASH_REMATCH[1]}" >> $GITHUB_OUTPUT
+            echo "minor=${BASH_REMATCH[2]}" >> $GITHUB_OUTPUT
+            echo "patch=${BASH_REMATCH[3]}" >> $GITHUB_OUTPUT
+          else
+            echo "Invalid semantic version tag: ${{ github.event.release.tag_name }}"
+            exit 1
+          fi
       - name: Log in to the Container registry
         uses: docker/login-action@v3
         with:
@@ -48,8 +59,10 @@ jobs:
           platforms: linux/arm64,linux/amd64
           push: true
           tags: |
-            ghcr.io/projectcims/cims-api:${{ steps.tag.outputs.prerelease == 'true' && 'prerelease' || 'latest' }}
-            ghcr.io/projectcims/cims-api:${{ steps.tag.outputs.tag }}
+            ghcr.io/projectcims/cims-api:${{ steps.release.outputs.prerelease == 'true' && 'prerelease' || 'latest' }}
+            ghcr.io/projectcims/cims-api:"${{ steps.semver.outputs.major }}"
+            ghcr.io/projectcims/cims-api:"${{ steps.semver.outputs.major }}.${{ steps.semver.outputs.minor }}"
+            ghcr.io/projectcims/cims-api:"${{ steps.semver.outputs.major }}.${{ steps.semver.outputs.minor }}.${{ steps.semver.outputs.patch }}"
       - name: Build and push Web Docker image
         uses: docker/build-push-action@v6
         with:
@@ -58,5 +71,7 @@ jobs:
           platforms: linux/arm64,linux/amd64
           push: true
           tags: |
-            ghcr.io/projectcims/cims-web:${{ steps.tag.outputs.prerelease == 'true' && 'prerelease' || 'latest' }}
-            ghcr.io/projectcims/cims-web:${{ steps.tag.outputs.tag }}
+            ghcr.io/projectcims/cims-web:${{ steps.release.outputs.prerelease == 'true' && 'prerelease' || 'latest' }}
+            ghcr.io/projectcims/cims-web:"${{ steps.semver.outputs.major }}"
+            ghcr.io/projectcims/cims-web:"${{ steps.semver.outputs.major }}.${{ steps.semver.outputs.minor }}"
+            ghcr.io/projectcims/cims-web:"${{ steps.semver.outputs.major }}.${{ steps.semver.outputs.minor }}.${{ steps.semver.outputs.patch }}"
